//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika_Cars.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fabrika_Cars.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About US.
        /// </summary>
        public static string AboutUS {
            get {
                return ResourceManager.GetString("AboutUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Are Company specilized in Selling and Advertising Cars Inside Egypt Countries.
        /// </summary>
        public static string aboutusTitle {
            get {
                return ResourceManager.GetString("aboutusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertise Name.
        /// </summary>
        public static string addName {
            get {
                return ResourceManager.GetString("addName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Advertisment.
        /// </summary>
        public static string addnewadd {
            get {
                return ResourceManager.GetString("addnewadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Number.
        /// </summary>
        public static string addnumber {
            get {
                return ResourceManager.GetString("addnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string addphoto {
            get {
                return ResourceManager.GetString("addphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anything online with Cars Arena.
        /// </summary>
        public static string anythingonlinewithCarsArena {
            get {
                return ResourceManager.GetString("anythingonlinewithCarsArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena.
        /// </summary>
        public static string Arena {
            get {
                return ResourceManager.GetString("Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMW.
        /// </summary>
        public static string BMW {
            get {
                return ResourceManager.GetString("BMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string cars {
            get {
                return ResourceManager.GetString("cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Arena.
        /// </summary>
        public static string carsarena {
            get {
                return ResourceManager.GetString("carsarena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chevrolet.
        /// </summary>
        public static string Chevrolet {
            get {
                return ResourceManager.GetString("Chevrolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me With.
        /// </summary>
        public static string ContactmeWith {
            get {
                return ResourceManager.GetString("ContactmeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Your Advertisment.
        /// </summary>
        public static string controlyouradd {
            get {
                return ResourceManager.GetString("controlyouradd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Free AD.
        /// </summary>
        public static string createfreeadd {
            get {
                return ResourceManager.GetString("createfreeadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create your add with carse arena.
        /// </summary>
        public static string createyouraddwithcarsarena {
            get {
                return ResourceManager.GetString("createyouraddwithcarsarena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteadd {
            get {
                return ResourceManager.GetString("deleteadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Advertisement.
        /// </summary>
        public static string descriptionadd {
            get {
                return ResourceManager.GetString("descriptionadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easiest.
        /// </summary>
        public static string Easiest {
            get {
                return ResourceManager.GetString("Easiest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elshorouk Academy.
        /// </summary>
        public static string ElshoroukAcademy {
            get {
                return ResourceManager.GetString("ElshoroukAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone.
        /// </summary>
        public static string Emailorphone {
            get {
                return ResourceManager.GetString("Emailorphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Address.
        /// </summary>
        public static string Enteryouraddress {
            get {
                return ResourceManager.GetString("Enteryouraddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email.
        /// </summary>
        public static string EnteryourEmail {
            get {
                return ResourceManager.GetString("EnteryourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Name.
        /// </summary>
        public static string EnteryourName {
            get {
                return ResourceManager.GetString("EnteryourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Password.
        /// </summary>
        public static string EnteryourPassword {
            get {
                return ResourceManager.GetString("EnteryourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone.
        /// </summary>
        public static string Enteryourphone {
            get {
                return ResourceManager.GetString("Enteryourphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Arena  App is the.
        /// </summary>
        public static string FabrikaCarsAppisthe {
            get {
                return ResourceManager.GetString("FabrikaCarsAppisthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda.
        /// </summary>
        public static string Honda {
            get {
                return ResourceManager.GetString("Honda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it Works.
        /// </summary>
        public static string HowitWorks {
            get {
                return ResourceManager.GetString("HowitWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyundai.
        /// </summary>
        public static string Hyundai {
            get {
                return ResourceManager.GetString("Hyundai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is Free.
        /// </summary>
        public static string ItisFree {
            get {
                return ResourceManager.GetString("ItisFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kia.
        /// </summary>
        public static string Kia {
            get {
                return ResourceManager.GetString("Kia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazda.
        /// </summary>
        public static string Mazda {
            get {
                return ResourceManager.GetString("Mazda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercedes.
        /// </summary>
        public static string Mercedes {
            get {
                return ResourceManager.GetString("Mercedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string myaccount {
            get {
                return ResourceManager.GetString("myaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nissan.
        /// </summary>
        public static string Nissan {
            get {
                return ResourceManager.GetString("Nissan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Advertise Have Been Added.
        /// </summary>
        public static string noadd {
            get {
                return ResourceManager.GetString("noadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Word Like This.
        /// </summary>
        public static string nowordlikeyoursearch {
            get {
                return ResourceManager.GetString("nowordlikeyoursearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opel.
        /// </summary>
        public static string opel {
            get {
                return ResourceManager.GetString("opel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our headquarters.
        /// </summary>
        public static string Ourheadquarters {
            get {
                return ResourceManager.GetString("Ourheadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peugeut.
        /// </summary>
        public static string peugeut {
            get {
                return ResourceManager.GetString("peugeut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Advertisement.
        /// </summary>
        public static string publishadd {
            get {
                return ResourceManager.GetString("publishadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publisher.
        /// </summary>
        public static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now In Cars Arena.
        /// </summary>
        public static string registernowincarsarena {
            get {
                return ResourceManager.GetString("registernowincarsarena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Price.
        /// </summary>
        public static string requiredprice {
            get {
                return ResourceManager.GetString("requiredprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string selectcategory {
            get {
                return ResourceManager.GetString("selectcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell or Advertise.
        /// </summary>
        public static string SellorAdvertise {
            get {
                return ResourceManager.GetString("SellorAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string sendmessage {
            get {
                return ResourceManager.GetString("sendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toyota.
        /// </summary>
        public static string Toyota {
            get {
                return ResourceManager.GetString("Toyota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control Panel.
        /// </summary>
        public static string usercontrolpanel {
            get {
                return ResourceManager.GetString("usercontrolpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volvo.
        /// </summary>
        public static string Volvo {
            get {
                return ResourceManager.GetString("Volvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to way for Selling and buying spare parts of cars.
        /// </summary>
        public static string wayforSellingandbuyingspaepartsofcars {
            get {
                return ResourceManager.GetString("wayforSellingandbuyingspaepartsofcars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Your Message.
        /// </summary>
        public static string writemessage {
            get {
                return ResourceManager.GetString("writemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Advertisment.
        /// </summary>
        public static string youradvertisment {
            get {
                return ResourceManager.GetString("youradvertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
