//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adv_copmanies
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public string car_category { get; set; }
        public Nullable<int> user_id { get; set; }
        public string connectwithmobile { get; set; }
        public string connectwithmail { get; set; }
        public string price { get; set; }
    
        public virtual users users { get; set; }
    }
}
