//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public string title { get; set; }
        public string msg { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
