//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika_Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sellers()
        {
            this.sellers_adv_copmanies = new HashSet<sellers_adv_copmanies>();
            this.buyer = new HashSet<buyer>();
        }
    
        public int id { get; set; }
        public string phonenumber { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string gernder { get; set; }
        public string post_time { get; set; }
        public string date_of_birth_ { get; set; }
        public string item_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sellers_adv_copmanies> sellers_adv_copmanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buyer> buyer { get; set; }
    }
}
